#!/usr/bin/env sh

set -e

uv run livist temperature
uv run livist temperature --to-wgs84
for path in data/*-wgs84.parquet; do
    "${GDAL:-gdal}" vector convert "$path" "${path%-wgs84.parquet}.fgb"
    tippecanoe -zg -o "${path%-wgs84.parquet}.pmtiles" "${path%-wgs84.parquet}.fgb"
done
