name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
        working-directory: frontend
      - name: Check
        run: scripts/check
      - name: Test
        run: uv run pytest
      - name: Build frontend
        run: yarn build
        working-directory: frontend
